name: FoodAndLove
favicon: null
layout_spectrum: 0.28511181683279574
typography_spectrum: 0.6401452559512109
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5da3a1'
    - '#347c7d'
    - '#111216'
    - '#b8dfdc'
    - '#1e5662'
  brandStrength: 0.625
  lightness: 0.9264785861596465
  saturation: 0.4206980965100229
  rhythmicContrast: 0.20208996231667697
purpose: []
